## loading and preprocessing data

In [2]:
import locale
import glob
import os.path
import requests
import tarfile
import sys
import codecs
from smart_open import smart_open
import re
import nltk
import numpy as np
import pickle
import itertools
from collections import Counter, OrderedDict
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from keras.preprocessing.sequence import pad_sequences
import re
from os import listdir
import string
from nltk.corpus import stopwords
from util.util_functions import getWordIdx, load_embedding_matrix_gensim
import gensim
import pickle
import keras
import tensorflow as tf
from keras.layers import Conv1D,Embedding,MaxPooling1D,Input
from keras.models import Model
import pandas as pd
from bs4 import BeautifulSoup
import string
from sklearn.model_selection import train_test_split

Using TensorFlow backend.
C:\Users\wyl19\Anaconda3\envs\tensorflow_cpu\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")


In [3]:
#define all of the functions
punctuation_list = list(string.punctuation)

# Convert text to lower-case and strip punctuation/symbols from words
def normalize_text(text):
#     norm_text = text.lower()
    # Replace breaks with spaces
    norm_text = text.replace('<br />', ' ')
    # Pad punctuation with spaces on both sides
    norm_text = re.sub(r"([\[\].\",()!?;:/])", " \\1 ", norm_text)
    return norm_text

def sent_tokenize(doc):
    sent_text = nltk.sent_tokenize(doc) # this gives you a list of sentences
    return sent_text

def word_tokenize(sent):
    tokenized_text = nltk.word_tokenize(sent)  # this gives you a list of words
    tokenized_text = [token.lower() for token in tokenized_text if token not in punctuation_list]  
    # optional: convert all words to lower case
    return tokenized_text

def readfile(filename):
    with open(filename,'r',encoding='UTF-8') as f:
        content = f.readlines()
    content = [x.strip() for x in content] 
    #strip()读出有效文件，形成一个list
    #split()读成有效文件，根据一行来形成一个list
    return content

#padding the sentence
#sentences是一个影评，就是一个train_data_word[0]
#max_words是影评中句子的最大含词量
#max_sents是影评中最大的句子个数
#保证每个影评的句子个数和句子长度都一样
def pad_sent(sentences, max_words, max_sents):
    """
    Pads sequences to the same length.
    Input: sentences - List of lists, where each element is a sequence.
    - max_words: Int, maximum length of all sequences.
    """
    # pad sentences in a doc
    sents_padded = pad_sequences(sentences, maxlen=max_words, padding='post') 
    # pad a doc to have equal number of sentences
    if len(sents_padded) < max_sents:
        doc_padding = np.zeros((max_sents-len(sents_padded),max_words), dtype = int)
        sents_padded = np.append(doc_padding, sents_padded, axis=0)
    else:
        sents_padded = sents_padded[:max_sents]
    return sents_padded

#build from word to integer as the input of ''
def build_vocab(corpus):
    """
    Builds a vocabulary mapping from word to index based on the corpus.
    Input: list of all samples in the training data
    Return: OrderedDict - vocabulary mapping from word to integer.
    """
    # Build vocabulary
    corpus_2d = []  # convert 3d corpus to 2d list
    for doc in corpus:
        for sent in doc:
            corpus_2d.append(sent)
    word_counts = Counter(itertools.chain(*corpus_2d))
    # Mapping from index to word (type: list)
    vocabulary = ['<PAD/>', '<UKN/>']   # 0 for padding, 1 for unknown words
    vocabulary = vocabulary + [x[0] for x in word_counts.most_common()]
    # Mapping from word to index
    #如何避免呢
    vocab2int = OrderedDict({x: i for i, x in enumerate(vocabulary)})
    return vocab2int

#****这个corpus是几维呢
def build_input_data(corpus, vocab2int, max_words, max_sents):
    """
    Maps words in the corpus to integers based on a vocabulary.
    Also pad the sentences and documents into fixed shape
    Input: corpus - list of samples, each sample is a list of sentences, each sentence is a list of words
    """
    corpus_int = [[[getWordIdx(word, vocab2int) for word in sentence]for sentence in sample] for sample in corpus]
    corpus_padded = []
    for doc in corpus_int:
        corpus_padded.append(pad_sent(doc, max_words, max_sents))
    corpus_padded = np.array(corpus_padded)    
    return corpus_padded

def load_embedding_matrix_gensim(embed_path, vocab2int, EMBEDDING_DIM):
    """
    load Word2Vec using gensim: 300x1 word vecs from Google (Mikolov) word2vec: GoogleNews-vectors-negative300.bin
    return embedding_matrix 
    embedding_matrix[i] is the embedding for 'vocab2int' integer index i
    """
    word2vec_model = gensim.models.KeyedVectors.load_word2vec_format(embed_path, binary=True)
    embeddings = {}
    embeddings['<PAD/>'] = np.zeros(EMBEDDING_DIM) # Zero vector for '<PAD/>' word
    embedding_UKN = np.random.uniform(-0.10, 0.10, EMBEDDING_DIM)  # Vector of small random numbers for unknown words
    # embedding_UKN = vector / np.linalg.norm(embedding_UKN)   # Normalize to unit vector
    embeddings['<UKN/>'] = embedding_UKN

    for word in word2vec_model.vocab:
        embeddings[word] = word2vec_model[word]

    embedding_matrix = np.zeros((len(vocab2int) , EMBEDDING_DIM))
    for word, i in vocab2int.items():
        embedding_vector = embeddings.get(word)
        if embedding_vector is not None:
            embedding_matrix[i] = embedding_vector
        else:   # word is unknown
            embedding_vector = np.random.uniform(-0.10, 0.10, EMBEDDING_DIM)  # Vector of small random numbers for unknown words
            # embedding_vector = vector / np.linalg.norm(embedding_vector)   # Normalize to unit vector
            embedding_matrix[i] = embedding_vector

    return embedding_matrix


In [7]:
#**********loading data
#get the movie review "list of string"
path_pos = 'data/unprocessed/sorted_data/apparel/positive.review'
path_neg = 'data/unprocessed/sorted_data/apparel/negative.review'

#read the file
file_pos = open(path_pos,'r',encoding='windows-1252')
file_pos = file_pos.read()

file_neg = open(path_neg,'r',encoding='windows-1252')
file_neg = file_neg.read()

#extact the file
positive = BeautifulSoup(file_pos)
positive = positive.find_all('review_text')#get all of the positive reviews
for i in range(len(positive)):#convet the elements in postive to the string type
    positive[i] = str(positive[i])

negative = BeautifulSoup(file_neg)
negative = negative.find_all('review_text')#get all the positive reviews
for i in range(len(negative)):#convet the elements in negative to the string type
    negative[i] = str(negative[i])
    
#eliminate the <review_text></review_text>tag in the reviews and normalize the text
positive_doc = []
for review in positive:
    review = normalize_text(review[14:-15])
    positive_doc.append(review)

negative_doc = []
for review in negative:
    review = normalize_text(review[14:-15])
    negative_doc.append(review)

#create the lable
train_pos_label =[1 for i in range(len(positive_doc))]
train_neg_label =[0 for i in range(len(negative_doc))]
    
#merge the data
train_data = positive_doc + negative_doc
train_label = train_pos_label + train_neg_label

#shuffle the data
from sklearn.utils import shuffle 
train_data , train_label = shuffle(train_data , train_label , random_state = 0) 

In [10]:
#tokenize the doc list to the list of sentences
train_data_sent = [sent_tokenize(train_data[i]) for i in range(len(train_data))]

#tokenize the two lists of list of sentences into two lists of list of list of word
train_data_word = [[]for i in range(len(train_data_sent))]
for i in range(len(train_data_sent)):
    for j in range(len(train_data_sent[i])):
        word_tokens = word_tokenize(train_data_sent[i][j])
        if word_tokens != []:
            train_data_word[i].append(word_tokens)  

In [17]:
#building the vacabulary
vocab_to_int = build_vocab(train_data_word)

#get the list which is the maxim quantity of sentence'
#get the padding element
maxlen_word = 0
maxlen_sent = 0

list_maxlen_sent = []
list_maxlen_word = []
for i in range(len(train_data_sent)):
    list_maxlen_sent.append((len(train_data_sent[i])))

#get the list which is the maxim quantity of word
for i in range(len(train_data_sent)):
    for j in range(len(train_data_sent[i])):
        list_maxlen_word.append(len(train_data_sent[i][j]))

#get the max sentence
list_maxlen_sent = sorted(list_maxlen_sent)
maxlen_sent = list_maxlen_sent[int(len(list_maxlen_sent)*0.95)]

#get the max words
list_maxlen_word1 = sorted(list_maxlen_word)
maxlen_word = list_maxlen_word[int(len(list_maxlen_word1)*0.95)]


#start to pad
copus_padded = build_input_data(corpus=train_data_word,max_sents=maxlen_sent,max_words=maxlen_word,vocab2int=vocab_to_int)

In [18]:
#display the data
print(copus_padded.shape)
print(train_data[8], '\n')
print(train_data_word[8], '\n')
print(copus_padded[8])

(2000, 13, 112)
 .  .  .  .  .  .  .  .  .  .  .  .  . they sent me the wrong size .  .  . and didn't leave clear returning guidelines .  You are better off getting something cheaper ,  because this sure as hell wasnt worth the buck 

[['they', 'sent', 'me', 'the', 'wrong', 'size'], ['and', 'did', "n't", 'leave', 'clear', 'returning', 'guidelines'], ['you', 'are', 'better', 'off', 'getting', 'something', 'cheaper', 'because', 'this', 'sure', 'as', 'hell', 'wasnt', 'worth', 'the', 'buck']] 

[[  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [ 12 255  48 ...   0   0   0]
 [  4  70  26 ...   0   0   0]
 [ 19  18 135 ...   0   0   0]]


In [20]:
# get the embedding matrix
# the number of the vocabulary is 100327
# 把每个词映射到一个300维度的vector
# 这个matrix是二维的
# 用vocab2int中每个词对应的整数来去matrix来找对应的vector
dimension = 300
path = 'E:/code_stock/SA/data/GoogleNews-vectors-negative300.bin'
embedding_matrix = load_embedding_matrix_gensim(embed_path = path,vocab2int=vocab_to_int,EMBEDDING_DIM=dimension)

#use pickle to store the data
file = open('pickle_New_Data/embedding_matrix','wb')     
pickle.dump(embedding_matrix,file)
file.close()

In [21]:
##### extract sentiment lexicons from SentiWordNet
file_path = 'resource/SentiWordNet_3.0.0_20130122.txt'
content = []
with open(file_path,'r',encoding='UTF-8') as f:
    while(1):
        lines = f.readline()
        if(lines[0] is ('a' or 'n' or 'v' or 'r')):
            content.append(lines.split('\t'))
        elif(lines[0] is '#'):
            continue
        else:
            break
             
#get the sentiment words(score>0.8)
neg_words1 = []
pos_words1 = []
for lines in content:
    if(float(lines[2])>=0.8):
        pos_words1.append(lines[4])
    elif(float(lines[3])>=0.8):
        neg_words1.append(lines[4])

#get the positive sentiment words
#seperate the multiple words
pos_words2 = []
for i in range(len(pos_words1)):
    pos_words2.append(pos_words1[i].split(' '))

#get the one dimension elements
pos_words3 = []
for i in pos_words2:
    for j in i:
        pos_words3.append(j)

#delete the '#4'
pos_words4 = []
for elem in pos_words3:
    pos_words4.append(re.sub('#\d','',elem))
    
#delete the 'number'
pos_lexicon = []
for elem in pos_words4:
    pos_lexicon.append(re.sub('\d','',elem))

    
#get the negative sentiment words
#seperate the multiple words
neg_words2 = []
for i in range(len(neg_words1)):
    neg_words2.append(neg_words1[i].split(' '))

#get the one dimension elements
neg_words3 = []
for i in neg_words2:
    for j in i:
        neg_words3.append(j)

#delete the '#4'
neg_words4 = []
for elem in neg_words3:
    neg_words4.append(re.sub('#\d','',elem))
    
#delete the 'number'
neg_lexicon = []
for elem in neg_words4:
    neg_lexicon.append(re.sub('\d','',elem))


print('pos lexicon no.:', len(pos_lexicon))
print('neg lexicon no.:', len(neg_lexicon))

#merge the positive and negative words
senti_lexicon = pos_lexicon + neg_lexicon


#create sentiment word filters
#map the sentiment words to integer based on vocab2int
senti2int = [getWordIdx(word, vocab_to_int) for word in senti_lexicon]

#get the filter weights based on the sentiment words&vocab2int&embedding_matrix
def Find_Filter_Weight(senti2int):
    """sentiwords is the list"""
    word_filter_weights = []
    bias_weights = []
    filter_len = 1
    for i in senti2int:
        vector = embedding_matrix[i]  # shape: 300
        vector = np.expand_dims(vector, axis=0) #shape: 1x 300
        vector = np.expand_dims(vector, axis=2) #shape: 1x 300 x 1
        if len(word_filter_weights) == 0:
            word_filter_weights = vector
        else:
            word_filter_weights = np.concatenate((word_filter_weights, vector), axis=2)
    #shape is (1, 300, 533)
    
    bias_weights = np.zeros(len(senti2int))
    cnn_wordfilter_weights = [word_filter_weights, bias_weights]
    
    return cnn_wordfilter_weights    

CNN_weights = Find_Filter_Weight(senti2int)

#store CNN_weights in pickle
file = open('pickle_New_Data/CNN_Weights.pickle','wb')     
pickle.dump(CNN_weights,file)
file.close()

pos lexicon no.: 161
neg lexicon no.: 372


In [39]:
CNN_weights[0].shape

(1, 300, 533)

In [24]:
#split the data to train and test dataset
train_copus_padded, test_copus_padded = train_test_split(copus_padded, train_size=0.9)
train_label, test_label = train_test_split(train_label,train_size=0.9)

C:\Users\wyl19\Anaconda3\envs\tensorflow_cpu\lib\site-packages\sklearn\model_selection\_split.py:2069: FutureWarning: From version 0.21, test_size will always complement train_size unless both are specified.
  FutureWarning)


In [38]:
#the shape of the data
print('train data shape:',train_copus_padded.shape)
print('test data shape:',test_copus_padded.shape)
print('embedding_matrix shape:', embedding_matrix.shape)
#the size of vocabulary
vocab_size = len(vocab_to_int)
print('vocabulary size:', vocab_size)
# the maximal length of every sentence
maxlen_sent = train_copus_padded.shape[1]
maxlen_word = train_copus_padded.shape[2]
print('max sent length:', maxlen_sent, '\nmax word length:', maxlen_word)

train data shape: (1800, 13, 112)
test data shape: (200, 13, 112)
embedding_matrix shape: (8023, 300)
vocabulary size: 8023
max sent length: 13 
max word length: 112


## building models 

In [27]:
import pickle
import keras
from keras.models import Sequential, Model
from keras.layers.core import Dense, Dropout, Activation, Flatten, Lambda
from keras.layers.embeddings import Embedding
from keras.layers import Convolution1D, MaxPooling1D, GlobalMaxPooling1D, Input, Dense, Reshape, LSTM, GRU, Bidirectional, TimeDistributed
from keras.layers.merge import concatenate, add
from keras.layers.normalization import BatchNormalization
from keras.utils import np_utils
from keras import initializers
from keras.engine.topology import Layer
from keras import backend as K
import tensorflow as tf
import numpy as np
from util.util_functions import getWordIdx
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import classification_report, roc_auc_score
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [28]:
class AttLayer(Layer):
    def __init__(self, attention_dim):
        self.init = initializers.get('normal')
        self.supports_masking = True
        self.attention_dim = attention_dim
        super(AttLayer, self).__init__()

    def build(self, input_shape):
        assert len(input_shape) == 3
        self.W = K.variable(self.init((input_shape[-1], self.attention_dim)))
        self.b = K.variable(self.init((self.attention_dim, )))
        self.u = K.variable(self.init((self.attention_dim, 1)))
        self.trainable_weights = [self.W, self.b, self.u]
        super(AttLayer, self).build(input_shape)

    def compute_mask(self, inputs, mask=None):
        return mask

    def call(self, x, mask=None):
        # size of x :[batch_size, sel_len, attention_dim]
        # size of u :[batch_size, attention_dim]
        # uit = tanh(xW+b)
        uit = K.tanh(K.bias_add(K.dot(x, self.W), self.b))
        ait = K.dot(uit, self.u)
        ait = K.squeeze(ait, -1)

        ait = K.exp(ait)

        if mask is not None:
            # Cast the mask to floatX to avoid float64 upcasting in theano
            ait *= K.cast(mask, K.floatx())
        ait /= K.cast(K.sum(ait, axis=1, keepdims=True) + K.epsilon(), K.floatx())
        ait = K.expand_dims(ait)
        weighted_input = x * ait
        output = K.sum(weighted_input, axis=1)

        return output

    def compute_output_shape(self, input_shape):
        return (input_shape[0], input_shape[-1])

In [40]:
# hyper-parameters
gru_dim = 50
dropout_rate = 0.2
atten_dim = 50

batch_size = 100
epoch_num = 10

categorical_label = True

if categorical_label:
    train_label_cat = np_utils.to_categorical(train_label)
    test_label_cat = np_utils.to_categorical(test_label)

## CNN+GRU

In [41]:
# define some Keras layers
embedding_layer = Embedding(vocab_size, embedding_matrix.shape[1], input_length= maxlen_word, 
                            weights=[embedding_matrix], trainable=False)

cnn_layer = Convolution1D(nb_filter=100,
                            filter_length=3,
                            border_mode='same',
                            activation='tanh',
                            subsample_length=1)

rnn_layer = Bidirectional(GRU(gru_dim, dropout=dropout_rate, recurrent_dropout=dropout_rate, return_sequences=True))
#embedding matrix shape[1]是300，每个vector的维度
max_pooling_layer = GlobalMaxPooling1D()


# build sentence encoder model
sentence_input = Input(shape=(maxlen_word,), dtype='int32')

sent_embedding = embedding_layer(sentence_input)  #input shape:(MAX_SENT_LENGTH),output shape:(MAX_SENT_LENGTH,embed dimension)

sent_cnn = cnn_layer(sent_embedding) # output shape: (None, maxlen_word, nb_filter)
# we use standard max over time pooling
sent_cnn = max_pooling_layer(sent_cnn)  # output shape: (None, nb_filter)


sentEncoder = Model(sentence_input, sent_cnn)
sentEncoder.summary()

# build document encoder model
review_input = Input(shape=(maxlen_sent, maxlen_word), dtype='int32')
review_encoder = TimeDistributed(sentEncoder)(review_input)   # out shape: (None, MAX_SENTS, nb_filter)

rnn_out = rnn_layer(review_encoder) # (batch_size, timesteps, gru_dimx2)

att_out = AttLayer(atten_dim)(rnn_out)

if categorical_label:
    preds = Dense(2, activation='softmax')(att_out) # categorical output
    model = Model(review_input, preds)
    model.compile(loss='categorical_crossentropy', optimizer='Adam', metrics=['acc'])
else:
    preds = Dense(1, activation='sigmoid')(att_out)
    model = Model(review_input, preds)
    model.compile(loss='binary_crossentropy', optimizer='Adam', metrics=['accuracy'])
    
model.summary()

C:\Users\wyl19\Anaconda3\envs\tensorflow_cpu\lib\site-packages\ipykernel\__main__.py:9: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(activation="tanh", filters=100, kernel_size=3, strides=1, padding="same")`


_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_9 (InputLayer)         (None, 112)               0         
_________________________________________________________________
embedding_5 (Embedding)      (None, 112, 300)          2406900   
_________________________________________________________________
conv1d_5 (Conv1D)            (None, 112, 100)          90100     
_________________________________________________________________
global_max_pooling1d_5 (Glob (None, 100)               0         
Total params: 2,497,000
Trainable params: 90,100
Non-trainable params: 2,406,900
_________________________________________________________________
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_10 (InputLayer)        (None, 13, 112)           0         
_____________________________________________________________

In [42]:
print('Training...')
for i in range(epoch_num):
    print('Training for epoch {}/{}'.format(i+1,epoch_num))
    if categorical_label:
        model.fit(train_copus_padded, train_label_cat, batch_size=batch_size,epochs=1)
    else:
        model.fit(train_copus_padded, train_label, batch_size=batch_size,epochs=1)
        
    print('Evaluating...')
    pred_test_prob = model.predict(test_copus_padded, batch_size=batch_size, verbose=True)
    # predict the class label
    if pred_test_prob.shape[-1]>1:
        pred_test = pred_test_prob.argmax(axis=-1)
    else:
        pred_test = (pred_test_prob>0.5).astype('int32')
        pred_test = pred_test.reshape(pred_test.shape[0])

    acc = np.sum(pred_test == test_label) / float(len(test_label))

    print("Accuracy: %.4f" % (acc))   
    print(classification_report(test_label, pred_test, digits=4, labels=[0, 1]))

Training...
Training for epoch 1/10
Epoch 1/1
1800/1800 [==============================] - 25s 14ms/step - loss: 0.6969 - acc: 0.5117
Evaluating...
200/200 [==============================] - 1s 7ms/step
Accuracy: 0.4650
              precision    recall  f1-score   support

           0     0.0000    0.0000    0.0000       107
           1     0.4650    1.0000    0.6348        93

   micro avg     0.4650    0.4650    0.4650       200
   macro avg     0.2325    0.5000    0.3174       200
weighted avg     0.2162    0.4650    0.2952       200

Training for epoch 2/10
Epoch 1/1


C:\Users\wyl19\Anaconda3\envs\tensorflow_cpu\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


1800/1800 [==============================] - 25s 14ms/step - loss: 0.6896 - acc: 0.5206
Evaluating...
200/200 [==============================] - 1s 5ms/step
Accuracy: 0.4650
              precision    recall  f1-score   support

           0     0.5000    0.0093    0.0183       107
           1     0.4646    0.9892    0.6323        93

   micro avg     0.4650    0.4650    0.4650       200
   macro avg     0.4823    0.4993    0.3253       200
weighted avg     0.4836    0.4650    0.3038       200

Training for epoch 3/10
Epoch 1/1
1800/1800 [==============================] - 25s 14ms/step - loss: 0.6856 - acc: 0.5428
Evaluating...
200/200 [==============================] - 1s 6ms/step
Accuracy: 0.5500
              precision    recall  f1-score   support

           0     0.5497    0.8785    0.6763       107
           1     0.5517    0.1720    0.2623        93

   micro avg     0.5500    0.5500    0.5500       200
   macro avg     0.5507    0.5253    0.4693       200
weighted avg     0.

## CNN 

## LSTM

## GRU

## biGRU

## K-CNN+biGRU

In [44]:
# define some Keras layers
embedding_layer = Embedding(vocab_size, embedding_matrix.shape[1], input_length=maxlen_word, 
                            weights=[embedding_matrix], trainable=False)

cnn_layer1 = Convolution1D(nb_filter=50,
                            filter_length=3,
                            border_mode='same',
                            activation='tanh',
                            subsample_length=1)

cnn_layer2 = Convolution1D(nb_filter=CNN_weights[0].shape[2],
                            filter_length=1,
                            border_mode='same',
                            activation='tanh',
                           weights = CNN_weights,
                           trainable = False,
                            subsample_length=1)

rnn_layer = Bidirectional(GRU(gru_dim, dropout=dropout_rate, recurrent_dropout=dropout_rate, return_sequences=True))
# rnn_layer = GRU(gru_dim, dropout=dropout_rate, recurrent_dropout=dropout_rate, return_sequences=True)

max_pooling_layer = GlobalMaxPooling1D()

C:\Users\wyl19\Anaconda3\envs\tensorflow_cpu\lib\site-packages\ipykernel\__main__.py:9: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(activation="tanh", filters=50, kernel_size=3, strides=1, padding="same")`
C:\Users\wyl19\Anaconda3\envs\tensorflow_cpu\lib\site-packages\ipykernel\__main__.py:17: UserWarning: Update your `Conv1D` call to the Keras 2 API: `Conv1D(activation="tanh", weights=[array([[[..., trainable=False, filters=533, kernel_size=1, strides=1, padding="same")`


In [45]:
# build sentence encoder model
sentence_input = Input(shape=(maxlen_word,), dtype='int32')

sent_embedding = embedding_layer(sentence_input)  #input shape:(MAX_SENT_LENGTH),output shape:(MAX_SENT_LENGTH,embed dimension)

sent_cnn1 = cnn_layer1(sent_embedding) # output shape: (None, maxlen_word, nb_filter)
# we use standard max over time pooling
sent_cnn1 = max_pooling_layer(sent_cnn1)  # output shape: (None, nb_filter)

sent_cnn2 = cnn_layer2(sent_embedding) # output shape: (None, maxlen_word, nb_filter)
# we use standard max over time pooling
sent_cnn2 = max_pooling_layer(sent_cnn2)  # output shape: (None, nb_filter)

sent_cnn = concatenate([sent_cnn1, sent_cnn2])

sentEncoder = Model(sentence_input, sent_cnn)
sentEncoder.summary()

__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_12 (InputLayer)           (None, 112)          0                                            
__________________________________________________________________________________________________
embedding_6 (Embedding)         (None, 112, 300)     2406900     input_12[0][0]                   
__________________________________________________________________________________________________
conv1d_6 (Conv1D)               (None, 112, 50)      45050       embedding_6[0][0]                
__________________________________________________________________________________________________
conv1d_7 (Conv1D)               (None, 112, 533)     160433      embedding_6[0][0]                
__________________________________________________________________________________________________
global_max

In [46]:
print('Training...')
for i in range(epoch_num):
    print('Training for epoch {}/{}'.format(i+1,epoch_num))
    if categorical_label:
        model.fit(train_copus_padded, train_label_cat, batch_size=batch_size,epochs=1)
    else:
        model.fit(train_copus_padded, train_label, batch_size=batch_size,epochs=1)
        
    print('Evaluating...')
    pred_test_prob = model.predict(test_copus_padded, batch_size=batch_size, verbose=True)
    # predict the class label
    if pred_test_prob.shape[-1]>1:
        pred_test = pred_test_prob.argmax(axis=-1)
    else:
        pred_test = (pred_test_prob>0.5).astype('int32')
        pred_test = pred_test.reshape(pred_test.shape[0])

    acc = np.sum(pred_test == test_label) / float(len(test_label))

    print("Accuracy: %.4f" % (acc))   
    print(classification_report(test_label, pred_test, digits=4, labels=[0, 1]))

Training...
Training for epoch 1/10
Epoch 1/1
1800/1800 [==============================] - 23s 13ms/step - loss: 0.1792 - acc: 0.9494
Evaluating...
200/200 [==============================] - 1s 5ms/step
Accuracy: 0.5250
              precision    recall  f1-score   support

           0     0.5833    0.3925    0.4693       107
           1     0.4922    0.6774    0.5701        93

   micro avg     0.5250    0.5250    0.5250       200
   macro avg     0.5378    0.5350    0.5197       200
weighted avg     0.5410    0.5250    0.5162       200

Training for epoch 2/10
Epoch 1/1
1800/1800 [==============================] - 27s 15ms/step - loss: 0.1620 - acc: 0.9561
Evaluating...
200/200 [==============================] - 1s 5ms/step
Accuracy: 0.5500
              precision    recall  f1-score   support

           0     0.5934    0.5047    0.5455       107
           1     0.5138    0.6022    0.5545        93

   micro avg     0.5500    0.5500    0.5500       200
   macro avg     0.5536    

KeyboardInterrupt: 

## biGRU+CNN

## CNN+biGRU